INSERT INTO utilities (slug, utility_type, name, logo_url, field_config, active)
VALUES
  ('mtn', 'airtime', 'MTN Airtime', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "amount_min_kobo": 5000, "amount_max_kobo": 5000000, "has_variations": false, "has_amount_picker": true, "icon_type": "airtime"}', true),
  ('airtel', 'airtime', 'Airtel Airtime', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "amount_min_kobo": 5000, "amount_max_kobo": 5000000, "has_variations": false, "has_amount_picker": true, "icon_type": "airtime"}', true),
  ('glo', 'airtime', 'Glo Airtime', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "amount_min_kobo": 5000, "amount_max_kobo": 5000000, "has_variations": false, "has_amount_picker": true, "icon_type": "airtime"}', true),
  ('9mobile', 'airtime', '9mobile Airtime', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "amount_min_kobo": 5000, "amount_max_kobo": 5000000, "has_variations": false, "has_amount_picker": true, "icon_type": "airtime"}', true),
  ('mtn-data', 'data', 'MTN Data', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "has_variations": true, "has_amount_picker": false, "icon_type": "data"}', true),
  ('airtel-data', 'data', 'Airtel Data', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "has_variations": true, "has_amount_picker": false, "icon_type": "data"}', true),
  ('glo-data', 'data', 'Glo Data', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "has_variations": true, "has_amount_picker": false, "icon_type": "data"}', true),
  ('9mobile-data', 'data', '9mobile Data', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "has_variations": true, "has_amount_picker": false, "icon_type": "data"}', true),
  ('dstv', 'dstv', 'DSTV', NULL, '{"service_ref_label": "Smartcard Number", "service_ref_placeholder": "e.g. 2012345678", "service_ref_pattern": "^[0-9]{10}$", "has_variations": true, "has_amount_picker": false, "icon_type": "tv"}', true),
  ('gotv', 'gotv', 'GOtv', NULL, '{"service_ref_label": "Smartcard Number", "service_ref_placeholder": "e.g. 2012345678", "service_ref_pattern": "^[0-9]{10}$", "has_variations": true, "has_amount_picker": false, "icon_type": "tv"}', true),
  ('startimes', 'startimes', 'Startimes', NULL, '{"service_ref_label": "Smartcard Number", "service_ref_placeholder": "e.g. 2012345678", "service_ref_pattern": "^[0-9]{10}$", "has_variations": true, "has_amount_picker": false, "icon_type": "tv"}', true),
  ('showmax', 'showmax', 'Showmax', NULL, '{"service_ref_label": "Email or Phone", "service_ref_placeholder": "you@email.com", "has_variations": true, "has_amount_picker": false, "icon_type": "tv"}', true),
  ('ikeja-electric', 'electricity', 'Ikeja Electric (IKEDC)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('eko-electric', 'electricity', 'Eko Electric (EKEDC)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('abuja-electric', 'electricity', 'Abuja Electric (AEDC)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('ibadan-electric', 'electricity', 'Ibadan Electric (IBEDC)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('kano-electric', 'electricity', 'Kano Electric (KEDCO)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('phed-electric', 'electricity', 'Port Harcourt Electric (PHED)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('jos-electric', 'electricity', 'Jos Electric (JED)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('kaduna-electric', 'electricity', 'Kaduna Electric (KAEDCO)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('enugu-electric', 'electricity', 'Enugu Electric (EEDC)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('benin-electric', 'electricity', 'Benin Electric (BEDC)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('yola-electric', 'electricity', 'Yola Electric (YEDC)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('aba-electric', 'electricity', 'Aba Electric (ABA)', NULL, '{"service_ref_label": "Meter Number", "service_ref_placeholder": "e.g. 54012345678", "service_ref_pattern": "^[0-9]{11,13}$", "amount_min_kobo": 50000, "amount_max_kobo": 50000000, "has_variations": false, "has_amount_picker": true, "icon_type": "electricity"}', true),
  ('waec-registration', 'waec', 'WAEC Registration', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "has_variations": true, "has_amount_picker": false, "icon_type": "education"}', true),
  ('waec-result-checker', 'waec', 'WAEC Result Checker', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "has_variations": true, "has_amount_picker": false, "icon_type": "education"}', true),
  ('jamb', 'jamb', 'JAMB Pin', NULL, '{"service_ref_label": "Phone Number", "service_ref_placeholder": "08012345678", "service_ref_pattern": "^0[7-9][0-1][0-9]{8}$", "has_variations": false, "has_amount_picker": false, "fixed_amount_kobo": 650000, "icon_type": "education"}', true),
  ('school-fees', 'school_fees', 'School Fees', NULL, '{"service_ref_label": "RRR or Student ID", "service_ref_placeholder": "Enter RRR or Student ID", "amount_min_kobo": 50000, "amount_max_kobo": 500000000, "has_variations": false, "has_amount_picker": true, "icon_type": "school"}', true)
ON CONFLICT (slug) DO UPDATE
SET
  utility_type = EXCLUDED.utility_type,
  name = EXCLUDED.name,
  logo_url = EXCLUDED.logo_url,
  field_config = EXCLUDED.field_config,
  active = EXCLUDED.active;

DELETE FROM utilities WHERE slug = 'phcn';
