ALTER TABLE rate_snapshots
  ADD COLUMN IF NOT EXISTS usd_kes NUMERIC(24, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS usd_ghs NUMERIC(24, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS usd_zar NUMERIC(24, 4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS usd_egp NUMERIC(24, 4) NOT NULL DEFAULT 0;
