services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zutility
    ports:
      - "5432:5432"
    volumes:
      - zutility-postgres-data:/var/lib/postgresql/data

volumes:
  zutility-postgres-data:
